SELECT TOP (1000) [Date Received]
      ,[Product Name]
      ,[Sub Product]
      ,[Issue]
      ,[Sub Issue]
      ,[Consumer Complaint Narrative]
      ,[Company Public Response]
      ,[Company]
      ,[State Name]
      ,[Zip Code]
      ,[Tags]
      ,[Consumer Consent Provided]
      ,[Submitted via]
      ,[Date Sent to Company]
      ,[Company Response to Consumer]
      ,[Timely Response]
      ,[Consumer Disputed]
      ,[Complaint ID]
  FROM [Consumers].[dbo].[RAW P9-Consumer]
